[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "panic=abort"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-cpu=native", "-C", "panic=abort"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+neon", "-C", "panic=abort"]

[target.armv7-unknown-linux-gnueabi]
rustflags = ["-C", "target-feature=+neon", "-C", "panic=abort"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon", "-C", "panic=abort"]
